apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sv4p2ors9-python
  janus-idp.io/tekton: sv4p2ors9-python
  backstage.io/kubernetes-id: sv4p2ors9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sv4p2ors9-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
